Repository DataBiosphere/hca-metadata-api, pull requests merged in 2020-11, with the labels that each got.

#25 Add support for 'submitter_id' field (#24)
  src/humancellatlas/data/metadata/api.py
  test/cans/prod/86e7b58e-b9f0-4020-8b34-c61d6da02d44/2019-09-20T103932.395795Z/metadata.json
  test/test.py
Labels: chain, orange

#30 Add donor_organism.development_stage (#26)
  src/humancellatlas/data/metadata/api.py
  test/test.py
Labels: 0 reviews, orange

#31 Add library_preparation_protocol.nucleic_acid_source (#27)
  src/humancellatlas/data/metadata/api.py
  test/test.py
Labels: orange

#23 Replace '!' with '/' in file names (#22)
  Makefile
  setup.py
  src/humancellatlas/data/metadata/api.py
  test/test.py
Labels: 2 reviews, orange
